m4_changequote(`[[', `]]')
m4_define([[PAGE_BG_COLOR]],[[#111]])
m4_define([[BODY_HOLDER_BG_COLOR]],[[#111]])
m4_define([[BODY_BG_COLOR]],[[#111]])
m4_define([[BORDER_COLOR]],[[#11F]])
m4_define([[BQ_BG_COLOR]],[[#222]])
m4_define([[BQ_BORDER_COLOR]],[[#333]])
m4_define([[A_COLOR]],[[#FFF]])
m4_define([[A_HOVER_COLOR]],[[#FFF]])
m4_define([[FONT_COLOR]],[[#0F0]])
m4_define([[FONT_LIST]],[[Monospace]])
