#!/usr/bin/env bash

source internal/globals.sh

set_editor

TEMP="$(mktemp)"
NOW=$(date +'%s')

TITLE="My Newest Post"
[[ "$@" != "" ]] && TITLE="$@"

cat << EOF > ${TEMP}
${NOW}
${NOW}
${DEFAULT_AUTHOR}
${TITLE}
${COMMENT_CODE} Create your post below. Lines beginning with "${COMMENT_CODE}"
${COMMENT_CODE} will be stripped out.
${COMMENT_CODE}
${COMMENT_CODE} Do not add any comments above the first four lines. The first four lines
${COMMENT_CODE} are special.
${COMMENT_CODE}
${COMMENT_CODE} 1. The initial posting timestamp
${COMMENT_CODE} 2. The last modified date
${COMMENT_CODE} 3. The author (feel free to change)
${COMMENT_CODE} 4. The title (feel free to change)
${COMMENT_CODE}
${COMMENT_CODE} Any remaining lines are considered the body. Any word
${COMMENT_CODE} preceeded by "${TAG_CODE}" will be treated as a tag. In the final HTML page,
${COMMENT_CODE} tags will have the preceeding "${TAG_CODE}" removed and hyperlinks added.
${COMMENT_CODE}
${COMMENT_CODE} You may manually specify where to end the homepage preview of this post by
${COMMENT_CODE} placing "${PREVIEW_STOP_CODE}" once somewhere. Otherwise, ${PREVIEW_MAX_WORDS} words will
${COMMENT_CODE} be used.
${COMMENT_CODE}
${COMMENT_CODE} Other than these special rules, use markdown to format your post.
EOF

"${ED}" "${TEMP}"

read -p "Would you like to save this post? " ANSWER
while [ 1 ]
do
	case $ANSWER in
		[Yy]* )
			POST_DATE=$(get_date ${TEMP})
			YEAR=$(date --date=@${POST_DATE} +'%Y')
			MONTH=$(date --date=@${POST_DATE} +'%m')
			mkdir -p "${POST_DIR}/${YEAR}/${MONTH}"
			TITLE=$(get_title "${TEMP}" | to_lower | strip_punctuation | strip_space)
			FILENAME="${POST_DIR}/${YEAR}/${MONTH}/${TITLE}${TITLE_SEPERATOR_CHAR}${RANDOM}.${POST_EXTENSION}"
			mv "${TEMP}" "${FILENAME}"
			make
			break;;
		[Nn]* )
			rm "${TEMP}"
			break;;
		* )
			echo "Please answer yes or no"
			read -p "Would you like to save this post? " ANSWER;;
	esac
done

