#!/usr/bin/env bash

source internal/globals.sh

set_editor

SEARCH_VALUE="$@"
SEARCH_VALUE="$(echo ${SEARCH_VALUE} | to_lower | strip_punctuation | strip_space)"

NUM_FOUND_FILES=$(find "${POST_DIR}" -type f -name "*${SEARCH_VALUE}*.${POST_EXTENSION}" | wc --lines)

if [[ "${NUM_FOUND_FILES}" == "1" ]]
then
	TEMP="$(mktemp)"
	FILE="$(find ${POST_DIR} -type f -name "*${SEARCH_VALUE}*.${POST_EXTENSION}")"
	cp "${FILE}" "${TEMP}"
	OLD_MOD_DATE="$(get_mod_date "${TEMP}")"
	${ED} "${TEMP}"
	sed -i "2,2{s/^${OLD_MOD_DATE}$/$(date +'%s')/;}" "${TEMP}"
	cp "${TEMP}" "${FILE}"
	rm "${TEMP}"
	make
elif [[ "${NUM_FOUND_FILES}" > "1" ]]
then
	echo "Ambiguous search term ${SEARCH_VALUE}"
	find ${POST_DIR} -type f -name "*${SEARCH_VALUE}*.${POST_EXTENSION}" -print0 | sort_by_date
else
	echo "Could not find posts matching ${SEARCH_VALUE}"
fi
