#!/usr/bin/env bash

source internal/globals.sh

SEARCH_VALUE="$@"
SEARCH_VALUE="$(echo ${SEARCH_VALUE} | to_lower | strip_punctuation | strip_space)"

NUM_FOUND_FILES=$(find "${POST_DIR}" -type f -name "*${SEARCH_VALUE}*.${POST_EXTENSION}" | wc --lines)

if [[ "${NUM_FOUND_FILES}" < "1" ]]
then
	echo "Could not find post matching: $@"
	exit 0

elif [[ "${NUM_FOUND_FILES}" == "1" ]]
then
	FILE="$(find ${POST_DIR} -type f -name "*${SEARCH_VALUE}*.${POST_EXTENSION}")"
elif [[ "${MULTI_MATCH_STRAT}" == "newest" ]]
then
	FILE="$(find ${POST_DIR} -type f -name "*${SEARCH_VALUE}*.${POST_EXTENSION}" -print0 | sort_by_date | tail -n 1)"

elif [[ "${MULTI_MATCH_STRAT}" == "oldest" ]]
then
	FILE="$(find ${POST_DIR} -type f -name "*${SEARCH_VALUE}*.${POST_EXTENSION}" -print0 | sort_by_date | head -n 1)"
else
	echo "Ambiguous search term: ${SEARCH_VALUE}"
	while read FILE
	do
		pretty_print_post_info "${FILE}"
	done < <(find ${POST_DIR} -type f -name "*${SEARCH_VALUE}*.${POST_EXTENSION}" -print0 | sort_by_date)
	exit 0
fi

[[ "${FILE}" == "" ]] && exit 0

echo ""
pretty_print_post_info "${FILE}"
echo ""
read -p "Are you sure you want to delete this post forever (a very long time)?" ANSWER
while [ 1 ]
do
	case $ANSWER in
		[Yy]* )
			rm "${FILE}"
			make clean
			make
			break;;
		* )
			echo "Whew. That was close."
			break;;
	esac
done
