#!/usr/bin/env bash

source internal/globals.sh

VALID_COMMANDS=( list set )
if [[ "$1" == "" ]]
then
	echo "Valid commadns are ${VALID_COMMANDS[@]}"
	exit 1
fi

[ -L "${THEME_SYMLINK}" ] &&
	SELECTED_THEME="$(realpath "${THEME_SYMLINK}")" ||
	SELECTED_THEME=

THEMES=( )
INDEX="0"
for THEME in $(find "${THEME_DIR}/" -mindepth 1 -maxdepth 1 -type d | sort)
do
	THEMES+=( "${INDEX}/${THEME}" )
	INDEX=$((INDEX+1))
done

if [[ "$1" == "list" ]]
then

	for THEME in ${THEMES[@]}
	do
		INDEX="$(echo ${THEME} | cut -d'/' -f 1)"
		THEME="$(echo ${THEME} | cut -d'/' -f 2-)"
		THEME_PATH="$(realpath "${THEME}")"
		THEME_NAME="$(basename "${THEME}")"
		[[ "${SELECTED_THEME}" == "${THEME_PATH}" ]] &&
			echo -n "--> " ||
			echo -n "    "
		echo [$INDEX] $THEME_NAME
	done

elif [[ "$1" == "set" ]]
then

	if [[ "$2" == "" ]]
	then
		echo "Need to provide an index"
		exit 1
	fi
	[ -L "${THEME_SYMLINK}" ] && rm "${THEME_SYMLINK}"
	THEME="$(echo ${THEMES[$2]} | cut -d'/' -f 2-)"
	THEME="$(basename "${THEME}")"
	ln -s "${THEME}" "${THEME_SYMLINK}"
	./bm theme list
fi

