m4_changequote(`[[', `]]')
m4_define([[PAGE_BG_COLOR]],[[#F3F3F3]])
m4_define([[BODY_HOLDER_BG_COLOR]],[[#DDD]])
m4_define([[BODY_BG_COLOR]],[[#FFF]])
m4_define([[BORDER_COLOR]],[[#CCC]])
m4_define([[BQ_BG_COLOR]],[[#F9F9F9]])
m4_define([[BQ_BORDER_COLOR]],[[#E9E9E9]])
m4_define([[A_COLOR]],[[#336699]])
m4_define([[A_HOVER_COLOR]],[[#5588bb]])
